export const symbols = {
	'Sidearm': { symbol: '', color: 'white'},
	'Submachine Gun': { symbol: '', color: 'white'},
	'Machine Gun': { symbol: '', color: 'white'},
	// 'Grenade Launcher': { symbol: '/', color: 'white'},
	'Grenade Launchers that use Special ammo': { symbol: '', color: 'white'},
	'Grenade Launchers that use Heavy ammo': { symbol: '', color: 'white'},
	'Sword': { symbol: '', color: 'white'},
	'Linear Fusion Rifle': { symbol: '', color: 'white'},
	'Fusion Rifle': { symbol: '', color: 'white'},
	'Shotgun': { symbol: '', color: 'white'},
	'Glaive': { symbol: '', color: 'white'},
	'Hand Cannon': { symbol: '', color: 'white'},
	'Pulse Rifle': { symbol: '', color: 'white'},
	'Scout Rifle': { symbol: '', color: 'white'},
	'Sniper Rifle': { symbol: '', color: 'white'},
	'Auto Rifle': { symbol: '', color: 'white'},
	'Rocket Launcher': { symbol: '', color: 'white'},
	'Bow': { symbol: '', color: 'white'},
	'Trace Rifle': { symbol: '', color: 'white'},
	'Solar': { symbol: '', color: '#E7601D'},
	'Void': { symbol: '', color: '#B07CDB'},
	'Arc': { symbol: '', color: '#81B5E4'},
	'Stasis': { symbol: '', color: '#5E7AFD'},
	// 'Kinetic': { symbol: '', color: 'white'},
	// 'Energy': { symbol: '', color: 'white'},
	'weapons': { symbol: '', color: 'white'},
	// 'Scorn': { symbol: '', color: 'white'},
	// 'Fallen': { symbol: '', color: 'white'},
	// 'Cabal': { symbol: '', color: 'white'},
	// 'Vex': { symbol: '', color: 'white'},
	// 'Taken': { symbol: '', color: 'white'},
	// 'Hive': { symbol: '', color: 'white'},
	// 'Super': { symbol: '', color: 'white'},
	// 'Orb': { symbol: '', color: 'white'},
	'melee': { symbol: '', color: 'white'},
	'grenade': { symbol: '', color: 'white'},
	// 'finisher': { symbol: '', color: 'white'},
	'precision': { symbol: '', color: 'white'},
	// 'public event': { symbol: '', color: 'white'},
	'Lost Sector': { symbol: '', color: 'white' },
}